apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  namespace: expense-dev
  labels:
    app: backend
spec:
  containers:
  - name: backend
    image: hashicorp/http-echo
    args:
      - "-text=Hello from Backend Pod"
    ports:
      - containerPort: 5678
