apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-agent
  template:
    metadata:
      labels:
        app: log-agent
    spec:
      containers:
      - name: agent
        image: busybox
        command: ["sh", "-c", "while true; do sleep 30; done"]
