apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-agent
  namespace: expense-dev
spec:
  selector:
    matchLabels:
      app: log-agent
  template:
    metadata:
      labels:
        app: log-agent
    spec:
      containers:
      - name: log-agent
        image: busybox
        command: ["sh", "-c", "while true; do echo log-agent running; sleep 30; done"]
