apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: expense-dev
  labels:
    name: nginx-demo
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-demo
      env: dev
  template:
    metadata:
      labels:
        name: nginx-demo
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        resources:
          requests:
            cpu: "100m"
            memory: "120Mi"
          limits:
            cpu: "120m"
            memory: "140Mi"
        ports:
        - containerPort: 80
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  namespace: expense-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-demo
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
