apiVersion: v1
kind: Pod
metadata:
  name: label
  labels:
    env: production
    tag: prod_db
spec:
  - containers:
    - name: app-data
      image: nginx
      port:    
        - containerPort: 80    
