apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80        # Service port
      targetPort: 80 # Pod port
      nodePort: 30080
