apiVersion: v1
kind: Pod
metadata:
  name: nodeaffinity-hard
  namespace: expense-dev
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: dedicated
            operator: In
            values:
            - db
  # Uncomment this if the node is tainted with: dedicated=db:NoSchedule
  # tolerations:
  # - key: "dedicated"
  #   operator: "Equal"
  #   value: "db"
  #   effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx:1.25
