apiVersion: v1 
kind: Pod
metadata:
  name: static-pod
  namespace: expense-dev
  labels:
    purpose: ebs-static
    project: expense
spec:
  container:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath : /user/share/nginx/html/
    volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: volume-Pod

        
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80     