apiVersion: v1
kind: Pod
metadata:
  name: static-pod
  namespace: expense-dev
  labels:
    purpose: ebs-static
    project: expense
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a   # must match EBS AZ
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: pod-pvc