apiVersion: v1 
kind: PersistentVolume
metadata:
  name: volume-Pod
spec:
  accessModes:
    - ReadWriteOnce
  capacity:  
    storage: 100Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle:
    
        