apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: expense-pod-reader 
  namespace: expense-dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: expense-pod-reader 
  namespace: expense-dev
subjects:
- kind: User
  name: harish
roleRef:
  kind: Role
  name: expense-pod-reader   
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: expense-cluster-reader 
rules:
- apiGroups: [""]
  resources: ["persistentvolumes", "nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: expense-cluster-reader 
subjects:
- kind: User
  name: harish
roleRef:
  kind: ClusterRole
  name: expense-cluster-reader   
  apiGroup: rbac.authorization.k8s.io
