apiVersion: v1
kind: Pod
metadata:
  name: Liveness-pod
spec:
  containers:
  - name: backend
    image: nginx
    ports:
    - containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 5
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
  
 
      