apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: nginx-rs 
  namespace: expense-dev
spec:
  replicas: 3
  matchLabels:
    labels: 
      name: nginx
      env: dev
template:
  metadata:
    labels:
      name: nginx
      env: dev
  spec:
    containers:
      name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80


