apiVersion: v1
kind: Pod
metadata:
  name: tolaration
  namespace: expense-dev
spec:
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "db"
    effect: "NoSchedule"
  nodeSelector:
    role: db  
  containers:
  - name: nginx
    image: nginx:1.25  